import pytest


SAMPLE_CARDS = [
    {
        "id": "a2daf943-dc88-4c8b-ac97-4476ea6abb9c",
        "oracle_id": "a2daf943-dc88-4c8b-ac97-4476ea6abb9c",
        "name": "Swords to Plowshares",
        "mana_cost": "{W}",
        "cmc": 1.0,
        "type_line": "Instant",
        "oracle_text": "Exile target creature. Its controller gains life equal to its power.",
        "colors": ["W"],
        "color_identity": ["W"],
        "keywords": [],
        "legalities": {"commander": "legal", "vintage": "legal", "legacy": "legal", "standard": "not_legal"},
        "rarity": "uncommon",
        "set": "c21",
        "scryfall_uri": "https://scryfall.com/card/c21/122/swords-to-plowshares",
        "image_uris": {"normal": "https://cards.scryfall.io/normal/front/a/2/a2daf943.jpg"},
        "layout": "normal",
    },
    {
        "id": "b9e60f82-a09d-4b68-b878-3e0b04be6b88",
        "oracle_id": "b9e60f82-a09d-4b68-b878-3e0b04be6b88",
        "name": "Sol Ring",
        "mana_cost": "{1}",
        "cmc": 1.0,
        "type_line": "Artifact",
        "oracle_text": "{T}: Add {C}{C}.",
        "colors": [],
        "color_identity": [],
        "keywords": [],
        "legalities": {"commander": "legal", "vintage": "restricted", "legacy": "banned", "standard": "not_legal"},
        "rarity": "uncommon",
        "set": "c21",
        "scryfall_uri": "https://scryfall.com/card/c21/264/sol-ring",
        "image_uris": {"normal": "https://cards.scryfall.io/normal/front/b/9/b9e60f82.jpg"},
        "layout": "normal",
    },
    {
        "id": "c5c61f6b-1234-4b68-b878-3e0b04be6b00",
        "oracle_id": "c5c61f6b-1234-4b68-b878-3e0b04be6b00",
        "name": "Teferi, Time Raveler",
        "mana_cost": "{1}{W}{U}",
        "cmc": 3.0,
        "type_line": "Legendary Planeswalker — Teferi",
        "oracle_text": "Each opponent can cast spells only any time they could cast a sorcery.\n+1: Until your next turn, you may cast instant spells as though they had flash.\n−3: Return up to one target artifact, creature, or enchantment to its owner's hand. Draw a card.",
        "colors": ["U", "W"],
        "color_identity": ["U", "W"],
        "keywords": [],
        "legalities": {"commander": "legal", "vintage": "legal", "legacy": "legal", "standard": "not_legal"},
        "rarity": "rare",
        "set": "war",
        "scryfall_uri": "https://scryfall.com/card/war/221/teferi-time-raveler",
        "image_uris": {"normal": "https://cards.scryfall.io/normal/front/c/5/c5c61f6b.jpg"},
        "layout": "normal",
        "loyalty": "4",
    },
    {
        "id": "d9d71f6b-5678-4b68-b878-3e0b04be6b11",
        "oracle_id": "d9d71f6b-5678-4b68-b878-3e0b04be6b11",
        "name": "Delver of Secrets // Insectile Aberration",
        "mana_cost": "{U}",
        "cmc": 1.0,
        "type_line": "Creature — Human Wizard // Creature — Human Insect",
        "oracle_text": "",
        "colors": ["U"],
        "color_identity": ["U"],
        "keywords": [],
        "legalities": {"commander": "legal", "vintage": "legal", "standard": "not_legal"},
        "rarity": "uncommon",
        "set": "isd",
        "scryfall_uri": "https://scryfall.com/card/isd/51/delver-of-secrets-insectile-aberration",
        "layout": "transform",
        "card_faces": [
            {
                "name": "Delver of Secrets",
                "mana_cost": "{U}",
                "type_line": "Creature — Human Wizard",
                "oracle_text": "At the beginning of your upkeep, look at the top card of your library. You may reveal that card. If an instant or sorcery card is revealed this way, transform Delver of Secrets.",
                "power": "1",
                "toughness": "1",
                "colors": ["U"],
                "image_uris": {"normal": "https://cards.scryfall.io/normal/front/d/9/d9d71f6b.jpg"},
            },
            {
                "name": "Insectile Aberration",
                "mana_cost": "",
                "type_line": "Creature — Human Insect",
                "oracle_text": "Flying",
                "power": "3",
                "toughness": "2",
                "colors": ["U"],
                "image_uris": {"normal": "https://cards.scryfall.io/normal/back/d/9/d9d71f6b.jpg"},
            },
        ],
    },
    {
        "id": "e1e11f6b-9999-4b68-b878-3e0b04be6b22",
        "oracle_id": "e1e11f6b-9999-4b68-b878-3e0b04be6b22",
        "name": "Cultivate",
        "mana_cost": "{2}{G}",
        "cmc": 3.0,
        "type_line": "Sorcery",
        "oracle_text": "Search your library for up to two basic land cards, reveal those cards, put one onto the battlefield tapped and the other into your hand, then shuffle.",
        "colors": ["G"],
        "color_identity": ["G"],
        "keywords": [],
        "legalities": {"commander": "legal", "vintage": "legal", "standard": "not_legal"},
        "rarity": "common",
        "set": "c21",
        "scryfall_uri": "https://scryfall.com/card/c21/162/cultivate",
        "image_uris": {"normal": "https://cards.scryfall.io/normal/front/e/1/e1e11f6b.jpg"},
        "layout": "normal",
    },
]
